### ISSUE TITLE
Ignore project if issue not present

### ISSUE THREAD

**Issue by koppor** [m7kvqbe1/github-action-move-issues#4]
Follow-up to https://github.com/m7kvqbe1/github-action-move-issues/issues/3

In our setting, we have two projects: "Good first issues" and "Candidates for University Projects". An issue can be in 0, 1, or 2 of these projects. In case a contributor is assigned, the "State" should change to "Assigned" in the projects to reflect the state "transparently" for the users.

I would like to move the issue only if it is already present in a board.

Proposal: If `ignored-columns` contains `<<not-in-project>>`, then the issue is not added to the project.

**Comment by koppor** [comment]
One can add an issue to a project with the GitHub CLI:

```yaml
  ui:
    if: "${{ github.event.label.name == 'ui' }}"
    runs-on: ubuntu-latest
    steps:
      - name: ui
        env:
          GH_DEBUG: api
          GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ITEM_ADD }}
        run: |
          ISSUE_URL=$(jq --raw-output .issue.html_url "$GITHUB_EVENT_PATH")
          echo $ISSUE_URL
          gh project item-add 8 --owner JabRef --url $ISSUE_URL
```

Therefore, it also would be OK for me that this action only moves issues if they are present in the project (and issues a warning output if the issue is not found in the given project).
